#pragma GCC poison CONFIG_AC97
#pragma GCC poison CONFIG_ACPI
#pragma GCC poison CONFIG_ACPI_CPU_HOTPLUG
#pragma GCC poison CONFIG_ACPI_ERST
#pragma GCC poison CONFIG_ACPI_HMAT
#pragma GCC poison CONFIG_ACPI_MEMORY_HOTPLUG
#pragma GCC poison CONFIG_ACPI_NVDIMM
#pragma GCC poison CONFIG_ACPI_PCI
#pragma GCC poison CONFIG_ACPI_PCIHP
#pragma GCC poison CONFIG_ACPI_PCI_BRIDGE
#pragma GCC poison CONFIG_ACPI_PIIX4
#pragma GCC poison CONFIG_ACPI_SMBUS
#pragma GCC poison CONFIG_ACPI_VIOT
#pragma GCC poison CONFIG_ACPI_VMCLOCK
#pragma GCC poison CONFIG_ACPI_VMGENID
#pragma GCC poison CONFIG_ACPI_X86
#pragma GCC poison CONFIG_APIC
#pragma GCC poison CONFIG_APM
#pragma GCC poison CONFIG_DIMM
#pragma GCC poison CONFIG_EDID
#pragma GCC poison CONFIG_GENERIC_LOADER
#pragma GCC poison CONFIG_HV_BALLOON_SUPPORTED
#pragma GCC poison CONFIG_I2C
#pragma GCC poison CONFIG_I386_DIS
#pragma GCC poison CONFIG_I8254
#pragma GCC poison CONFIG_I8257
#pragma GCC poison CONFIG_I8259
#pragma GCC poison CONFIG_IDE_BUS
#pragma GCC poison CONFIG_IDE_CF
#pragma GCC poison CONFIG_IDE_CORE
#pragma GCC poison CONFIG_IDE_DEV
#pragma GCC poison CONFIG_IDE_PCI
#pragma GCC poison CONFIG_IDE_PIIX
#pragma GCC poison CONFIG_IMX_USBPHY
#pragma GCC poison CONFIG_IOAPIC
#pragma GCC poison CONFIG_ISA_BUS
#pragma GCC poison CONFIG_MC146818RTC
#pragma GCC poison CONFIG_MEM_DEVICE
#pragma GCC poison CONFIG_MSI_NONBROKEN
#pragma GCC poison CONFIG_PAM
#pragma GCC poison CONFIG_PC
#pragma GCC poison CONFIG_PCI
#pragma GCC poison CONFIG_PCI_I440FX
#pragma GCC poison CONFIG_PCI_TESTDEV
#pragma GCC poison CONFIG_PCKBD
#pragma GCC poison CONFIG_PCSPK
#pragma GCC poison CONFIG_PC_ACPI
#pragma GCC poison CONFIG_PC_PCI
#pragma GCC poison CONFIG_PFLASH_CFI01
#pragma GCC poison CONFIG_PIIX
#pragma GCC poison CONFIG_PS2
#pragma GCC poison CONFIG_SCSI
#pragma GCC poison CONFIG_SERIAL
#pragma GCC poison CONFIG_SERIAL_ISA
#pragma GCC poison CONFIG_SMBUS
#pragma GCC poison CONFIG_SMBUS_EEPROM
#pragma GCC poison CONFIG_SPDM_SOCKET
#pragma GCC poison CONFIG_SYSTEM_ONLY
#pragma GCC poison CONFIG_USB
#pragma GCC poison CONFIG_USB_AUDIO
#pragma GCC poison CONFIG_USB_CANOKEY
#pragma GCC poison CONFIG_USB_HID
#pragma GCC poison CONFIG_USB_HUB
#pragma GCC poison CONFIG_USB_NETWORK
#pragma GCC poison CONFIG_USB_OHCI
#pragma GCC poison CONFIG_USB_OHCI_PCI
#pragma GCC poison CONFIG_USB_SERIAL
#pragma GCC poison CONFIG_USB_SMARTCARD
#pragma GCC poison CONFIG_USB_STORAGE_BOT
#pragma GCC poison CONFIG_USB_STORAGE_CLASSIC
#pragma GCC poison CONFIG_USB_STORAGE_CORE
#pragma GCC poison CONFIG_USB_STORAGE_MTP
#pragma GCC poison CONFIG_USB_STORAGE_UAS
#pragma GCC poison CONFIG_USB_TABLET_WACOM
#pragma GCC poison CONFIG_USB_U2F
#pragma GCC poison CONFIG_USB_UHCI
#pragma GCC poison CONFIG_VGA
#pragma GCC poison CONFIG_VGA_PCI
#pragma GCC poison CONFIG_VIRTIO_MEM_SUPPORTED
#pragma GCC poison CONFIG_VIRTIO_PMEM_SUPPORTED
#pragma GCC poison CONFIG_WDT_IB700
#pragma GCC poison CONFIG_XBOX
#pragma GCC poison QEMU_ARCH
#pragma GCC poison TARGET_BIG_ENDIAN
#pragma GCC poison TARGET_I386
#pragma GCC poison TARGET_KVM_HAVE_GUEST_DEBUG
#pragma GCC poison TARGET_KVM_HAVE_RESET_PARKED_VCPU
#pragma GCC poison TARGET_LONG_BITS
#pragma GCC poison TARGET_NAME
