# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/claude/xemu-libretro
TARGET_DIRS=i386-softmmu
GDB=
SUBDIRS=
PYTHON=/home/claude/xemu-libretro/build-w64/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/claude/xemu-libretro/build-w64/pyvenv/bin/python3 -B /home/claude/xemu-libretro/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=
MESON=/home/claude/xemu-libretro/build-w64/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=.exe
TCG_TESTS_WITH_COMPILERS=
