/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_XBOX_MCPX_APU_DSP_GENERATED_TRACERS_H
#define TRACE_HW_XBOX_MCPX_APU_DSP_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_DSP_READ_PERIPHERAL_EVENT;
extern TraceEvent _TRACE_DSP_WRITE_PERIPHERAL_EVENT;
extern TraceEvent _TRACE_DSP56K_EXECUTE_INSTRUCTION_EVENT;
extern TraceEvent _TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_EVENT;
extern uint16_t _TRACE_DSP_READ_PERIPHERAL_DSTATE;
extern uint16_t _TRACE_DSP_WRITE_PERIPHERAL_DSTATE;
extern uint16_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DSTATE;
extern uint16_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_DSTATE;
#define TRACE_DSP_READ_PERIPHERAL_ENABLED 1
#define TRACE_DSP_WRITE_PERIPHERAL_ENABLED 1
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_ENABLED 1
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_DSP_READ_PERIPHERAL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DSP_READ_PERIPHERAL) || \
    false)

static inline void trace_dsp_read_peripheral(uint32_t addr, uint32_t val)
{
    if (trace_event_get_state(TRACE_DSP_READ_PERIPHERAL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/xbox/mcpx/apu/dsp/trace-events"
            qemu_log("dsp_read_peripheral " "addr 0x%"PRIx32" val 0x%"PRIx32 "\n", addr, val);
#line 35 "trace/trace-hw_xbox_mcpx_apu_dsp.h"
        }
    }
}

#define TRACE_DSP_WRITE_PERIPHERAL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DSP_WRITE_PERIPHERAL) || \
    false)

static inline void trace_dsp_write_peripheral(uint32_t addr, uint32_t val)
{
    if (trace_event_get_state(TRACE_DSP_WRITE_PERIPHERAL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../hw/xbox/mcpx/apu/dsp/trace-events"
            qemu_log("dsp_write_peripheral " "addr 0x%"PRIx32" val 0x%"PRIx32 "\n", addr, val);
#line 50 "trace/trace-hw_xbox_mcpx_apu_dsp.h"
        }
    }
}

#define TRACE_DSP56K_EXECUTE_INSTRUCTION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DSP56K_EXECUTE_INSTRUCTION) || \
    false)

static inline void trace_dsp56k_execute_instruction(uint32_t id, uint32_t pc)
{
    if (trace_event_get_state(TRACE_DSP56K_EXECUTE_INSTRUCTION)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../hw/xbox/mcpx/apu/dsp/trace-events"
            qemu_log("dsp56k_execute_instruction " "[gp=%d]: pc=0x%"PRIx32 "\n", id, pc);
#line 65 "trace/trace-hw_xbox_mcpx_apu_dsp.h"
        }
    }
}

#define TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM) || \
    false)

static inline void trace_dsp56k_execute_instruction_disasm(const char *disasm)
{
    if (trace_event_get_state(TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "../hw/xbox/mcpx/apu/dsp/trace-events"
            qemu_log("dsp56k_execute_instruction_disasm " "%s" "\n", disasm);
#line 80 "trace/trace-hw_xbox_mcpx_apu_dsp.h"
        }
    }
}
#endif /* TRACE_HW_XBOX_MCPX_APU_DSP_GENERATED_TRACERS_H */
