/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-hw_xbox_mcpx_nvnet.h"

uint16_t _TRACE_NVNET_PHY_REG_READ_DSTATE;
uint16_t _TRACE_NVNET_PHY_REG_WRITE_DSTATE;
uint16_t _TRACE_NVNET_REG_READ_DSTATE;
uint16_t _TRACE_NVNET_REG_WRITE_DSTATE;
uint16_t _TRACE_NVNET_IO_READ_DSTATE;
uint16_t _TRACE_NVNET_IO_WRITE_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_BCAST_MATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_MCAST_MATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_UCAST_MATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_OVERSIZED_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_DROPPED_DSTATE;
uint16_t _TRACE_NVNET_LINK_NEGOTIATION_START_DSTATE;
uint16_t _TRACE_NVNET_LINK_NEGOTIATION_DONE_DSTATE;
uint16_t _TRACE_NVNET_LINK_STATUS_CHANGED_DSTATE;
uint16_t _TRACE_NVNET_CANT_RX_DSTATE;
uint16_t _TRACE_NVNET_CANT_TX_DSTATE;
uint16_t _TRACE_NVNET_UPDATE_IRQ_DSTATE;
uint16_t _TRACE_NVNET_DESC_STORE_DSTATE;
uint16_t _TRACE_NVNET_RX_DMA_DSTATE;
uint16_t _TRACE_NVNET_TX_DMA_DSTATE;
uint16_t _TRACE_NVNET_PACKET_TX_DSTATE;
TraceEvent _TRACE_NVNET_PHY_REG_READ_EVENT = {
    .id = 0,
    .name = "nvnet_phy_reg_read",
    .sstate = TRACE_NVNET_PHY_REG_READ_ENABLED,
    .dstate = &_TRACE_NVNET_PHY_REG_READ_DSTATE
};
TraceEvent _TRACE_NVNET_PHY_REG_WRITE_EVENT = {
    .id = 0,
    .name = "nvnet_phy_reg_write",
    .sstate = TRACE_NVNET_PHY_REG_WRITE_ENABLED,
    .dstate = &_TRACE_NVNET_PHY_REG_WRITE_DSTATE
};
TraceEvent _TRACE_NVNET_REG_READ_EVENT = {
    .id = 0,
    .name = "nvnet_reg_read",
    .sstate = TRACE_NVNET_REG_READ_ENABLED,
    .dstate = &_TRACE_NVNET_REG_READ_DSTATE
};
TraceEvent _TRACE_NVNET_REG_WRITE_EVENT = {
    .id = 0,
    .name = "nvnet_reg_write",
    .sstate = TRACE_NVNET_REG_WRITE_ENABLED,
    .dstate = &_TRACE_NVNET_REG_WRITE_DSTATE
};
TraceEvent _TRACE_NVNET_IO_READ_EVENT = {
    .id = 0,
    .name = "nvnet_io_read",
    .sstate = TRACE_NVNET_IO_READ_ENABLED,
    .dstate = &_TRACE_NVNET_IO_READ_DSTATE
};
TraceEvent _TRACE_NVNET_IO_WRITE_EVENT = {
    .id = 0,
    .name = "nvnet_io_write",
    .sstate = TRACE_NVNET_IO_WRITE_ENABLED,
    .dstate = &_TRACE_NVNET_IO_WRITE_DSTATE
};
TraceEvent _TRACE_NVNET_RX_FILTER_BCAST_MATCH_EVENT = {
    .id = 0,
    .name = "nvnet_rx_filter_bcast_match",
    .sstate = TRACE_NVNET_RX_FILTER_BCAST_MATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_BCAST_MATCH_DSTATE
};
TraceEvent _TRACE_NVNET_RX_FILTER_MCAST_MATCH_EVENT = {
    .id = 0,
    .name = "nvnet_rx_filter_mcast_match",
    .sstate = TRACE_NVNET_RX_FILTER_MCAST_MATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_MCAST_MATCH_DSTATE
};
TraceEvent _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_EVENT = {
    .id = 0,
    .name = "nvnet_rx_filter_mcast_mismatch",
    .sstate = TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_DSTATE
};
TraceEvent _TRACE_NVNET_RX_FILTER_UCAST_MATCH_EVENT = {
    .id = 0,
    .name = "nvnet_rx_filter_ucast_match",
    .sstate = TRACE_NVNET_RX_FILTER_UCAST_MATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_UCAST_MATCH_DSTATE
};
TraceEvent _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_EVENT = {
    .id = 0,
    .name = "nvnet_rx_filter_ucast_mismatch",
    .sstate = TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_DSTATE
};
TraceEvent _TRACE_NVNET_RX_OVERSIZED_EVENT = {
    .id = 0,
    .name = "nvnet_rx_oversized",
    .sstate = TRACE_NVNET_RX_OVERSIZED_ENABLED,
    .dstate = &_TRACE_NVNET_RX_OVERSIZED_DSTATE
};
TraceEvent _TRACE_NVNET_RX_FILTER_DROPPED_EVENT = {
    .id = 0,
    .name = "nvnet_rx_filter_dropped",
    .sstate = TRACE_NVNET_RX_FILTER_DROPPED_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_DROPPED_DSTATE
};
TraceEvent _TRACE_NVNET_LINK_NEGOTIATION_START_EVENT = {
    .id = 0,
    .name = "nvnet_link_negotiation_start",
    .sstate = TRACE_NVNET_LINK_NEGOTIATION_START_ENABLED,
    .dstate = &_TRACE_NVNET_LINK_NEGOTIATION_START_DSTATE
};
TraceEvent _TRACE_NVNET_LINK_NEGOTIATION_DONE_EVENT = {
    .id = 0,
    .name = "nvnet_link_negotiation_done",
    .sstate = TRACE_NVNET_LINK_NEGOTIATION_DONE_ENABLED,
    .dstate = &_TRACE_NVNET_LINK_NEGOTIATION_DONE_DSTATE
};
TraceEvent _TRACE_NVNET_LINK_STATUS_CHANGED_EVENT = {
    .id = 0,
    .name = "nvnet_link_status_changed",
    .sstate = TRACE_NVNET_LINK_STATUS_CHANGED_ENABLED,
    .dstate = &_TRACE_NVNET_LINK_STATUS_CHANGED_DSTATE
};
TraceEvent _TRACE_NVNET_CANT_RX_EVENT = {
    .id = 0,
    .name = "nvnet_cant_rx",
    .sstate = TRACE_NVNET_CANT_RX_ENABLED,
    .dstate = &_TRACE_NVNET_CANT_RX_DSTATE
};
TraceEvent _TRACE_NVNET_CANT_TX_EVENT = {
    .id = 0,
    .name = "nvnet_cant_tx",
    .sstate = TRACE_NVNET_CANT_TX_ENABLED,
    .dstate = &_TRACE_NVNET_CANT_TX_DSTATE
};
TraceEvent _TRACE_NVNET_UPDATE_IRQ_EVENT = {
    .id = 0,
    .name = "nvnet_update_irq",
    .sstate = TRACE_NVNET_UPDATE_IRQ_ENABLED,
    .dstate = &_TRACE_NVNET_UPDATE_IRQ_DSTATE
};
TraceEvent _TRACE_NVNET_DESC_STORE_EVENT = {
    .id = 0,
    .name = "nvnet_desc_store",
    .sstate = TRACE_NVNET_DESC_STORE_ENABLED,
    .dstate = &_TRACE_NVNET_DESC_STORE_DSTATE
};
TraceEvent _TRACE_NVNET_RX_DMA_EVENT = {
    .id = 0,
    .name = "nvnet_rx_dma",
    .sstate = TRACE_NVNET_RX_DMA_ENABLED,
    .dstate = &_TRACE_NVNET_RX_DMA_DSTATE
};
TraceEvent _TRACE_NVNET_TX_DMA_EVENT = {
    .id = 0,
    .name = "nvnet_tx_dma",
    .sstate = TRACE_NVNET_TX_DMA_ENABLED,
    .dstate = &_TRACE_NVNET_TX_DMA_DSTATE
};
TraceEvent _TRACE_NVNET_PACKET_TX_EVENT = {
    .id = 0,
    .name = "nvnet_packet_tx",
    .sstate = TRACE_NVNET_PACKET_TX_ENABLED,
    .dstate = &_TRACE_NVNET_PACKET_TX_DSTATE
};
TraceEvent *hw_xbox_mcpx_nvnet_trace_events[] = {
    &_TRACE_NVNET_PHY_REG_READ_EVENT,
    &_TRACE_NVNET_PHY_REG_WRITE_EVENT,
    &_TRACE_NVNET_REG_READ_EVENT,
    &_TRACE_NVNET_REG_WRITE_EVENT,
    &_TRACE_NVNET_IO_READ_EVENT,
    &_TRACE_NVNET_IO_WRITE_EVENT,
    &_TRACE_NVNET_RX_FILTER_BCAST_MATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_MCAST_MATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_UCAST_MATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_EVENT,
    &_TRACE_NVNET_RX_OVERSIZED_EVENT,
    &_TRACE_NVNET_RX_FILTER_DROPPED_EVENT,
    &_TRACE_NVNET_LINK_NEGOTIATION_START_EVENT,
    &_TRACE_NVNET_LINK_NEGOTIATION_DONE_EVENT,
    &_TRACE_NVNET_LINK_STATUS_CHANGED_EVENT,
    &_TRACE_NVNET_CANT_RX_EVENT,
    &_TRACE_NVNET_CANT_TX_EVENT,
    &_TRACE_NVNET_UPDATE_IRQ_EVENT,
    &_TRACE_NVNET_DESC_STORE_EVENT,
    &_TRACE_NVNET_RX_DMA_EVENT,
    &_TRACE_NVNET_TX_DMA_EVENT,
    &_TRACE_NVNET_PACKET_TX_EVENT,
  NULL,
};

static void trace_hw_xbox_mcpx_nvnet_register_events(void)
{
    trace_event_register_group(hw_xbox_mcpx_nvnet_trace_events);
}
trace_init(trace_hw_xbox_mcpx_nvnet_register_events)
