/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-hw_xbox_mcpx_apu_dsp.h"

uint16_t _TRACE_DSP_READ_PERIPHERAL_DSTATE;
uint16_t _TRACE_DSP_WRITE_PERIPHERAL_DSTATE;
uint16_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DSTATE;
uint16_t _TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_DSTATE;
TraceEvent _TRACE_DSP_READ_PERIPHERAL_EVENT = {
    .id = 0,
    .name = "dsp_read_peripheral",
    .sstate = TRACE_DSP_READ_PERIPHERAL_ENABLED,
    .dstate = &_TRACE_DSP_READ_PERIPHERAL_DSTATE
};
TraceEvent _TRACE_DSP_WRITE_PERIPHERAL_EVENT = {
    .id = 0,
    .name = "dsp_write_peripheral",
    .sstate = TRACE_DSP_WRITE_PERIPHERAL_ENABLED,
    .dstate = &_TRACE_DSP_WRITE_PERIPHERAL_DSTATE
};
TraceEvent _TRACE_DSP56K_EXECUTE_INSTRUCTION_EVENT = {
    .id = 0,
    .name = "dsp56k_execute_instruction",
    .sstate = TRACE_DSP56K_EXECUTE_INSTRUCTION_ENABLED,
    .dstate = &_TRACE_DSP56K_EXECUTE_INSTRUCTION_DSTATE
};
TraceEvent _TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_EVENT = {
    .id = 0,
    .name = "dsp56k_execute_instruction_disasm",
    .sstate = TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_ENABLED,
    .dstate = &_TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_DSTATE
};
TraceEvent *hw_xbox_mcpx_apu_dsp_trace_events[] = {
    &_TRACE_DSP_READ_PERIPHERAL_EVENT,
    &_TRACE_DSP_WRITE_PERIPHERAL_EVENT,
    &_TRACE_DSP56K_EXECUTE_INSTRUCTION_EVENT,
    &_TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_EVENT,
  NULL,
};

static void trace_hw_xbox_mcpx_apu_dsp_register_events(void)
{
    trace_event_register_group(hw_xbox_mcpx_apu_dsp_trace_events);
}
trace_init(trace_hw_xbox_mcpx_apu_dsp_register_events)
