/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_ACCEL_HVF_GENERATED_TRACERS_H
#define TRACE_ACCEL_HVF_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_HVF_VM_MAP_EVENT;
extern TraceEvent _TRACE_HVF_VM_UNMAP_EVENT;
extern uint16_t _TRACE_HVF_VM_MAP_DSTATE;
extern uint16_t _TRACE_HVF_VM_UNMAP_DSTATE;
#define TRACE_HVF_VM_MAP_ENABLED 1
#define TRACE_HVF_VM_UNMAP_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_HVF_VM_MAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HVF_VM_MAP) || \
    false)

static inline void trace_hvf_vm_map(uint64_t paddr, uint64_t size, void *vaddr, uint8_t flags, const char r, const char w, const char e)
{
    if (trace_event_get_state(TRACE_HVF_VM_MAP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../accel/hvf/trace-events"
            qemu_log("hvf_vm_map " "paddr:0x%016"PRIx64" size:0x%08"PRIx64" vaddr:%p flags:0x%02x/%c%c%c" "\n", paddr, size, vaddr, flags, r, w, e);
#line 29 "trace/trace-accel_hvf.h"
        }
    }
}

#define TRACE_HVF_VM_UNMAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HVF_VM_UNMAP) || \
    false)

static inline void trace_hvf_vm_unmap(uint64_t paddr, uint64_t size)
{
    if (trace_event_get_state(TRACE_HVF_VM_UNMAP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../accel/hvf/trace-events"
            qemu_log("hvf_vm_unmap " "paddr:0x%016"PRIx64" size:0x%08"PRIx64 "\n", paddr, size);
#line 44 "trace/trace-accel_hvf.h"
        }
    }
}
#endif /* TRACE_ACCEL_HVF_GENERATED_TRACERS_H */
