/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_XBOX_NV2A_GENERATED_TRACERS_H
#define TRACE_HW_XBOX_NV2A_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_NV2A_REG_READ_EVENT;
extern TraceEvent _TRACE_NV2A_REG_WRITE_EVENT;
extern TraceEvent _TRACE_NV2A_IRQ_EVENT;
extern TraceEvent _TRACE_NV2A_DMA_MAP_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_METHOD_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_METHOD_ABBREV_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_TARGET_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_FLIP_STALL_EVENT;
extern TraceEvent _TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_EVENT;
extern uint16_t _TRACE_NV2A_REG_READ_DSTATE;
extern uint16_t _TRACE_NV2A_REG_WRITE_DSTATE;
extern uint16_t _TRACE_NV2A_IRQ_DSTATE;
extern uint16_t _TRACE_NV2A_DMA_MAP_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_METHOD_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_METHOD_ABBREV_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_TARGET_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_FLIP_STALL_DSTATE;
extern uint16_t _TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_DSTATE;
#define TRACE_NV2A_REG_READ_ENABLED 1
#define TRACE_NV2A_REG_WRITE_ENABLED 1
#define TRACE_NV2A_IRQ_ENABLED 1
#define TRACE_NV2A_DMA_MAP_ENABLED 1
#define TRACE_NV2A_PGRAPH_METHOD_ENABLED 1
#define TRACE_NV2A_PGRAPH_METHOD_ABBREV_ENABLED 1
#define TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_TARGET_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_ENABLED 1
#define TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_ENABLED 1
#define TRACE_NV2A_PGRAPH_FLIP_STALL_ENABLED 1
#define TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_NV2A_REG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_REG_READ) || \
    false)

static inline void trace_nv2a_reg_read(const char *block, uint32_t addr, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_NV2A_REG_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_reg_read " "%s addr 0x%"PRIx32" size %d val 0x%"PRIx64 "\n", block, addr, size, val);
#line 104 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_REG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_REG_WRITE) || \
    false)

static inline void trace_nv2a_reg_write(const char *block, uint32_t addr, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_NV2A_REG_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_reg_write " "%s addr 0x%"PRIx32" size %d val 0x%"PRIx64 "\n", block, addr, size, val);
#line 119 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_IRQ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_IRQ) || \
    false)

static inline void trace_nv2a_irq(uint32_t pending)
{
    if (trace_event_get_state(TRACE_NV2A_IRQ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_irq " "%08"PRIx32 "\n", pending);
#line 134 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_DMA_MAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_DMA_MAP) || \
    false)

static inline void trace_nv2a_dma_map(uint32_t obj_address, uint32_t dma_class, uint32_t dma_target, uint32_t dma_addr, uint32_t dma_limit)
{
    if (trace_event_get_state(TRACE_NV2A_DMA_MAP)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_dma_map " "obj 0x%08"PRIx32" class 0x%08"PRIx32" target 0x%08"PRIx32" addr 0x%08"PRIx32" limit 0x%08"PRIx32 "\n", obj_address, dma_class, dma_target, dma_addr, dma_limit);
#line 149 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_METHOD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_METHOD) || \
    false)

static inline void trace_nv2a_pgraph_method(uint32_t subchannel, uint32_t graphics_class, uint32_t method, const char *name, uint32_t offset, uint32_t parameter)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_METHOD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_method " "%d: 0x%"PRIx32" -> 0x%04"PRIx32" %s[%"PRId32"] 0x%"PRIx32 "\n", subchannel, graphics_class, method, name, offset, parameter);
#line 164 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_METHOD_ABBREV_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_METHOD_ABBREV) || \
    false)

static inline void trace_nv2a_pgraph_method_abbrev(uint32_t subchannel, uint32_t graphics_class, uint32_t method, const char *name, unsigned int count)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_METHOD_ABBREV)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_method_abbrev " "%d: 0x%"PRIx32" -> 0x%04"PRIx32" %s * %d" "\n", subchannel, graphics_class, method, name, count);
#line 179 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_METHOD_UNHANDLED) || \
    false)

static inline void trace_nv2a_pgraph_method_unhandled(uint32_t subchannel, uint32_t graphics_class, uint32_t method, uint32_t parameter)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_METHOD_UNHANDLED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_method_unhandled " "%d: 0x%"PRIx32" -> 0x%04"PRIx32" 0x%"PRIx32 "\n", subchannel, graphics_class, method, parameter);
#line 194 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH) || \
    false)

static inline void trace_nv2a_pgraph_surface_compare_mismatch(const char *field, long int a, long int b)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_compare_mismatch " "%20s -- %8ld vs %8ld" "\n", field, a, b);
#line 209 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_CPU_READ) || \
    false)

static inline void trace_nv2a_pgraph_surface_cpu_read(uint32_t addr, uint32_t offset)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_CPU_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_cpu_read " "0x%08"PRIx32"+0x%"PRIx32 "\n", addr, offset);
#line 224 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE) || \
    false)

static inline void trace_nv2a_pgraph_surface_cpu_write(uint32_t addr, uint32_t offset)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_cpu_write " "0x%08"PRIx32"+0x%"PRIx32 "\n", addr, offset);
#line 239 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR) || \
    false)

static inline void trace_nv2a_pgraph_surface_create_color(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_create_color " "Create: [COLOR @ 0x%08" PRIx32 " (%dx%d)] (%s) aa:%d, clip:x=%d,w=%d,y=%d,h=%d,p=%d" "\n", addr, width, height, layout, anti_aliasing, clip_x, clip_width, clip_y, clip_height, pitch);
#line 254 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA) || \
    false)

static inline void trace_nv2a_pgraph_surface_create_zeta(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_create_zeta " " Create: [ZETA  @ 0x%08" PRIx32 " (%dx%d)] (%s) aa:%d, clip:x=%d,w=%d,y=%d,h=%d,p=%d" "\n", addr, width, height, layout, anti_aliasing, clip_x, clip_width, clip_y, clip_height, pitch);
#line 269 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD) || \
    false)

static inline void trace_nv2a_pgraph_surface_download(const char *binding, const char *layout, uint32_t addr, uint32_t width, uint32_t height, uint32_t pitch, uint32_t bytes_per_pixel)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_download " "[GPU->RAM] %s (%s) surface @ 0x%08" PRIx32 " (w=%d,h=%d,p=%d,bpp=%d)" "\n", binding, layout, addr, width, height, pitch, bytes_per_pixel);
#line 284 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING) || \
    false)

static inline void trace_nv2a_pgraph_surface_evict_overlapping(uint32_t addr, uint32_t width, uint32_t height, uint32_t pitch)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_evict_overlapping " "Evicting overlapping surface @ 0x%08" PRIx32 " (%dx%d,p=%d)" "\n", addr, width, height, pitch);
#line 299 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON) || \
    false)

static inline void trace_nv2a_pgraph_surface_evict_reason(const char *reason, uint32_t addr)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 20 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_evict_reason " "Evicting %s surface @ 0x%08" PRIx32 "\n", reason, addr);
#line 314 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR) || \
    false)

static inline void trace_nv2a_pgraph_surface_hit_color(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 21 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_hit_color " "   Hit: [COLOR @ 0x%08" PRIx32 " (%dx%d)] (%s) aa:%d, clip:x=%d,w=%d,y=%d,h=%d,p=%d" "\n", addr, width, height, layout, anti_aliasing, clip_x, clip_width, clip_y, clip_height, pitch);
#line 329 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA) || \
    false)

static inline void trace_nv2a_pgraph_surface_hit_zeta(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_hit_zeta " "    Hit: [ZETA  @ 0x%08" PRIx32 " (%dx%d)] (%s) aa:%d, clip:x=%d,w=%d,y=%d,h=%d,p=%d" "\n", addr, width, height, layout, anti_aliasing, clip_x, clip_width, clip_y, clip_height, pitch);
#line 344 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED) || \
    false)

static inline void trace_nv2a_pgraph_surface_invalidated(uint32_t addr)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 23 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_invalidated " "0x%08"PRIx32 "\n", addr);
#line 359 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR) || \
    false)

static inline void trace_nv2a_pgraph_surface_match_color(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 24 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_match_color " " Match: [COLOR @ 0x%08" PRIx32 " (%dx%d)] (%s) aa:%d clip:x=%d,w=%d,y=%d,h=%d,p=%d" "\n", addr, width, height, layout, anti_aliasing, clip_x, clip_width, clip_y, clip_height, pitch);
#line 374 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA) || \
    false)

static inline void trace_nv2a_pgraph_surface_match_zeta(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 25 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_match_zeta " "  Match: [ZETA  @ 0x%08" PRIx32 " (%dx%d)] (%s) aa:%d clip:x=%d,w=%d,y=%d,h=%d,p=%d" "\n", addr, width, height, layout, anti_aliasing, clip_x, clip_width, clip_y, clip_height, pitch);
#line 389 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE) || \
    false)

static inline void trace_nv2a_pgraph_surface_migrate_type(const char *new_type)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 26 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_migrate_type " "Migrating surface type to %s" "\n", new_type);
#line 404 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE) || \
    false)

static inline void trace_nv2a_pgraph_surface_render_to_texture(uint32_t addr, uint32_t width, uint32_t height)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 27 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_render_to_texture " "Rendering surface 0x%08" PRIx32 " to texture (%dx%d)" "\n", addr, width, height);
#line 419 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_TARGET_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_TARGET) || \
    false)

static inline void trace_nv2a_pgraph_surface_target(const char *binding, uint32_t addr, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_TARGET)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 28 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_target " "      Target: [%-5s @ 0x%08" PRIx32 "] (%s) aa:%d clip:x=%d,w=%d,y=%d,h=%d" "\n", binding, addr, layout, anti_aliasing, clip_x, clip_width, clip_y, clip_height);
#line 434 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED) || \
    false)

static inline void trace_nv2a_pgraph_surface_texture_compat_failed(int32_t surface_fmt, int32_t texture_fmt)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 29 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_texture_compat_failed " "Surface->Texture compat failed: %x to %x" "\n", surface_fmt, texture_fmt);
#line 449 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_SURFACE_UPLOAD) || \
    false)

static inline void trace_nv2a_pgraph_surface_upload(const char *binding, const char *layout, uint32_t addr, uint32_t width, uint32_t height, uint32_t pitch, uint32_t bytes_per_pixel)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_SURFACE_UPLOAD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 30 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_surface_upload " "[RAM->GPU] %s (%s) surface @ 0x%08" PRIx32 " (w=%d,h=%d,p=%d,bpp=%d)" "\n", binding, layout, addr, width, height, pitch, bytes_per_pixel);
#line 464 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_FLIP_STALL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_FLIP_STALL) || \
    false)

static inline void trace_nv2a_pgraph_flip_stall(void)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_FLIP_STALL)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 31 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_flip_stall " "" "\n");
#line 479 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}

#define TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE) || \
    false)

static inline void trace_nv2a_pgraph_flip_increment_write(uint32_t write3d_old, uint32_t write3d_new)
{
    if (trace_event_get_state(TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 32 "../hw/xbox/nv2a/trace-events"
            qemu_log("nv2a_pgraph_flip_increment_write " "0x%"PRIx32" -> 0x%"PRIx32 "\n", write3d_old, write3d_new);
#line 494 "trace/trace-hw_xbox_nv2a.h"
        }
    }
}
#endif /* TRACE_HW_XBOX_NV2A_GENERATED_TRACERS_H */
