/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_XBOX_MCPX_APU_GENERATED_TRACERS_H
#define TRACE_HW_XBOX_MCPX_APU_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_MCPX_APU_METHOD_EVENT;
extern TraceEvent _TRACE_MCPX_APU_REG_READ_EVENT;
extern TraceEvent _TRACE_MCPX_APU_REG_WRITE_EVENT;
extern uint16_t _TRACE_MCPX_APU_METHOD_DSTATE;
extern uint16_t _TRACE_MCPX_APU_REG_READ_DSTATE;
extern uint16_t _TRACE_MCPX_APU_REG_WRITE_DSTATE;
#define TRACE_MCPX_APU_METHOD_ENABLED 1
#define TRACE_MCPX_APU_REG_READ_ENABLED 1
#define TRACE_MCPX_APU_REG_WRITE_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_MCPX_APU_METHOD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MCPX_APU_METHOD) || \
    false)

static inline void trace_mcpx_apu_method(uint32_t addr, uint32_t parameter)
{
    if (trace_event_get_state(TRACE_MCPX_APU_METHOD)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/xbox/mcpx/apu/trace-events"
            qemu_log("mcpx_apu_method " "0x%04"PRIx32" 0x%"PRIx32 "\n", addr, parameter);
#line 32 "trace/trace-hw_xbox_mcpx_apu.h"
        }
    }
}

#define TRACE_MCPX_APU_REG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MCPX_APU_REG_READ) || \
    false)

static inline void trace_mcpx_apu_reg_read(uint32_t addr, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_MCPX_APU_REG_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../hw/xbox/mcpx/apu/trace-events"
            qemu_log("mcpx_apu_reg_read " "addr 0x%"PRIx32" size %d val 0x%"PRIx64 "\n", addr, size, val);
#line 47 "trace/trace-hw_xbox_mcpx_apu.h"
        }
    }
}

#define TRACE_MCPX_APU_REG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_MCPX_APU_REG_WRITE) || \
    false)

static inline void trace_mcpx_apu_reg_write(uint32_t addr, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_MCPX_APU_REG_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../hw/xbox/mcpx/apu/trace-events"
            qemu_log("mcpx_apu_reg_write " "addr 0x%"PRIx32" size %d val 0x%"PRIx64 "\n", addr, size, val);
#line 62 "trace/trace-hw_xbox_mcpx_apu.h"
        }
    }
}
#endif /* TRACE_HW_XBOX_MCPX_APU_GENERATED_TRACERS_H */
