/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_HW_XBOX_MCPX_NVNET_GENERATED_TRACERS_H
#define TRACE_HW_XBOX_MCPX_NVNET_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_NVNET_PHY_REG_READ_EVENT;
extern TraceEvent _TRACE_NVNET_PHY_REG_WRITE_EVENT;
extern TraceEvent _TRACE_NVNET_REG_READ_EVENT;
extern TraceEvent _TRACE_NVNET_REG_WRITE_EVENT;
extern TraceEvent _TRACE_NVNET_IO_READ_EVENT;
extern TraceEvent _TRACE_NVNET_IO_WRITE_EVENT;
extern TraceEvent _TRACE_NVNET_RX_FILTER_BCAST_MATCH_EVENT;
extern TraceEvent _TRACE_NVNET_RX_FILTER_MCAST_MATCH_EVENT;
extern TraceEvent _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_EVENT;
extern TraceEvent _TRACE_NVNET_RX_FILTER_UCAST_MATCH_EVENT;
extern TraceEvent _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_EVENT;
extern TraceEvent _TRACE_NVNET_RX_OVERSIZED_EVENT;
extern TraceEvent _TRACE_NVNET_RX_FILTER_DROPPED_EVENT;
extern TraceEvent _TRACE_NVNET_LINK_NEGOTIATION_START_EVENT;
extern TraceEvent _TRACE_NVNET_LINK_NEGOTIATION_DONE_EVENT;
extern TraceEvent _TRACE_NVNET_LINK_STATUS_CHANGED_EVENT;
extern TraceEvent _TRACE_NVNET_CANT_RX_EVENT;
extern TraceEvent _TRACE_NVNET_CANT_TX_EVENT;
extern TraceEvent _TRACE_NVNET_UPDATE_IRQ_EVENT;
extern TraceEvent _TRACE_NVNET_DESC_STORE_EVENT;
extern TraceEvent _TRACE_NVNET_RX_DMA_EVENT;
extern TraceEvent _TRACE_NVNET_TX_DMA_EVENT;
extern TraceEvent _TRACE_NVNET_PACKET_TX_EVENT;
extern uint16_t _TRACE_NVNET_PHY_REG_READ_DSTATE;
extern uint16_t _TRACE_NVNET_PHY_REG_WRITE_DSTATE;
extern uint16_t _TRACE_NVNET_REG_READ_DSTATE;
extern uint16_t _TRACE_NVNET_REG_WRITE_DSTATE;
extern uint16_t _TRACE_NVNET_IO_READ_DSTATE;
extern uint16_t _TRACE_NVNET_IO_WRITE_DSTATE;
extern uint16_t _TRACE_NVNET_RX_FILTER_BCAST_MATCH_DSTATE;
extern uint16_t _TRACE_NVNET_RX_FILTER_MCAST_MATCH_DSTATE;
extern uint16_t _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_DSTATE;
extern uint16_t _TRACE_NVNET_RX_FILTER_UCAST_MATCH_DSTATE;
extern uint16_t _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_DSTATE;
extern uint16_t _TRACE_NVNET_RX_OVERSIZED_DSTATE;
extern uint16_t _TRACE_NVNET_RX_FILTER_DROPPED_DSTATE;
extern uint16_t _TRACE_NVNET_LINK_NEGOTIATION_START_DSTATE;
extern uint16_t _TRACE_NVNET_LINK_NEGOTIATION_DONE_DSTATE;
extern uint16_t _TRACE_NVNET_LINK_STATUS_CHANGED_DSTATE;
extern uint16_t _TRACE_NVNET_CANT_RX_DSTATE;
extern uint16_t _TRACE_NVNET_CANT_TX_DSTATE;
extern uint16_t _TRACE_NVNET_UPDATE_IRQ_DSTATE;
extern uint16_t _TRACE_NVNET_DESC_STORE_DSTATE;
extern uint16_t _TRACE_NVNET_RX_DMA_DSTATE;
extern uint16_t _TRACE_NVNET_TX_DMA_DSTATE;
extern uint16_t _TRACE_NVNET_PACKET_TX_DSTATE;
#define TRACE_NVNET_PHY_REG_READ_ENABLED 1
#define TRACE_NVNET_PHY_REG_WRITE_ENABLED 1
#define TRACE_NVNET_REG_READ_ENABLED 1
#define TRACE_NVNET_REG_WRITE_ENABLED 1
#define TRACE_NVNET_IO_READ_ENABLED 1
#define TRACE_NVNET_IO_WRITE_ENABLED 1
#define TRACE_NVNET_RX_FILTER_BCAST_MATCH_ENABLED 1
#define TRACE_NVNET_RX_FILTER_MCAST_MATCH_ENABLED 1
#define TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_ENABLED 1
#define TRACE_NVNET_RX_FILTER_UCAST_MATCH_ENABLED 1
#define TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_ENABLED 1
#define TRACE_NVNET_RX_OVERSIZED_ENABLED 1
#define TRACE_NVNET_RX_FILTER_DROPPED_ENABLED 1
#define TRACE_NVNET_LINK_NEGOTIATION_START_ENABLED 1
#define TRACE_NVNET_LINK_NEGOTIATION_DONE_ENABLED 1
#define TRACE_NVNET_LINK_STATUS_CHANGED_ENABLED 1
#define TRACE_NVNET_CANT_RX_ENABLED 1
#define TRACE_NVNET_CANT_TX_ENABLED 1
#define TRACE_NVNET_UPDATE_IRQ_ENABLED 1
#define TRACE_NVNET_DESC_STORE_ENABLED 1
#define TRACE_NVNET_RX_DMA_ENABLED 1
#define TRACE_NVNET_TX_DMA_ENABLED 1
#define TRACE_NVNET_PACKET_TX_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_NVNET_PHY_REG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_PHY_REG_READ) || \
    false)

static inline void trace_nvnet_phy_reg_read(unsigned int phy_addr, uint8_t addr, const char *name, uint16_t val)
{
    if (trace_event_get_state(TRACE_NVNET_PHY_REG_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_phy_reg_read " "phy %d addr 0x%"PRIx8" %s val 0x%"PRIx16 "\n", phy_addr, addr, name, val);
#line 92 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_PHY_REG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_PHY_REG_WRITE) || \
    false)

static inline void trace_nvnet_phy_reg_write(unsigned int phy_addr, uint8_t addr, const char *name, uint16_t val)
{
    if (trace_event_get_state(TRACE_NVNET_PHY_REG_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_phy_reg_write " "phy %d addr 0x%"PRIx8" %s val 0x%"PRIx16 "\n", phy_addr, addr, name, val);
#line 107 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_REG_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_REG_READ) || \
    false)

static inline void trace_nvnet_reg_read(uint32_t addr, const char *name, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_NVNET_REG_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_reg_read " "addr 0x%"PRIx32" %s size %d val 0x%"PRIx64 "\n", addr, name, size, val);
#line 122 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_REG_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_REG_WRITE) || \
    false)

static inline void trace_nvnet_reg_write(uint32_t addr, const char *name, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_NVNET_REG_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_reg_write " "addr 0x%"PRIx32" %s size %d val 0x%"PRIx64 "\n", addr, name, size, val);
#line 137 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_IO_READ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_IO_READ) || \
    false)

static inline void trace_nvnet_io_read(uint32_t addr, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_NVNET_IO_READ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_io_read " "addr 0x%"PRIx32" size %d val 0x%"PRIx64 "\n", addr, size, val);
#line 152 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_IO_WRITE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_IO_WRITE) || \
    false)

static inline void trace_nvnet_io_write(uint32_t addr, unsigned int size, uint64_t val)
{
    if (trace_event_get_state(TRACE_NVNET_IO_WRITE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_io_write " "addr 0x%"PRIx32" size %d val 0x%"PRIx64 "\n", addr, size, val);
#line 167 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_FILTER_BCAST_MATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_FILTER_BCAST_MATCH) || \
    false)

static inline void trace_nvnet_rx_filter_bcast_match(void)
{
    if (trace_event_get_state(TRACE_NVNET_RX_FILTER_BCAST_MATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_filter_bcast_match " "broadcast match" "\n");
#line 182 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_FILTER_MCAST_MATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_FILTER_MCAST_MATCH) || \
    false)

static inline void trace_nvnet_rx_filter_mcast_match(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3, uint8_t b4, uint8_t b5)
{
    if (trace_event_get_state(TRACE_NVNET_RX_FILTER_MCAST_MATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_filter_mcast_match " "multicast match: %02x:%02x:%02x:%02x:%02x:%02x" "\n", b0, b1, b2, b3, b4, b5);
#line 197 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_FILTER_MCAST_MISMATCH) || \
    false)

static inline void trace_nvnet_rx_filter_mcast_mismatch(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3, uint8_t b4, uint8_t b5)
{
    if (trace_event_get_state(TRACE_NVNET_RX_FILTER_MCAST_MISMATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_filter_mcast_mismatch " "multicast mismatch: %02x:%02x:%02x:%02x:%02x:%02x" "\n", b0, b1, b2, b3, b4, b5);
#line 212 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_FILTER_UCAST_MATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_FILTER_UCAST_MATCH) || \
    false)

static inline void trace_nvnet_rx_filter_ucast_match(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3, uint8_t b4, uint8_t b5)
{
    if (trace_event_get_state(TRACE_NVNET_RX_FILTER_UCAST_MATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_filter_ucast_match " "unicast match: %02x:%02x:%02x:%02x:%02x:%02x" "\n", b0, b1, b2, b3, b4, b5);
#line 227 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_FILTER_UCAST_MISMATCH) || \
    false)

static inline void trace_nvnet_rx_filter_ucast_mismatch(uint8_t b0, uint8_t b1, uint8_t b2, uint8_t b3, uint8_t b4, uint8_t b5)
{
    if (trace_event_get_state(TRACE_NVNET_RX_FILTER_UCAST_MISMATCH)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_filter_ucast_mismatch " "unicast mismatch: %02x:%02x:%02x:%02x:%02x:%02x" "\n", b0, b1, b2, b3, b4, b5);
#line 242 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_OVERSIZED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_OVERSIZED) || \
    false)

static inline void trace_nvnet_rx_oversized(size_t size)
{
    if (trace_event_get_state(TRACE_NVNET_RX_OVERSIZED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_oversized " "Received packet dropped because it was oversized (%zu bytes)" "\n", size);
#line 257 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_FILTER_DROPPED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_FILTER_DROPPED) || \
    false)

static inline void trace_nvnet_rx_filter_dropped(void)
{
    if (trace_event_get_state(TRACE_NVNET_RX_FILTER_DROPPED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_filter_dropped " "Received packet dropped by RX filter" "\n");
#line 272 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_LINK_NEGOTIATION_START_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_LINK_NEGOTIATION_START) || \
    false)

static inline void trace_nvnet_link_negotiation_start(void)
{
    if (trace_event_get_state(TRACE_NVNET_LINK_NEGOTIATION_START)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_link_negotiation_start " "Start link auto negotiation" "\n");
#line 287 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_LINK_NEGOTIATION_DONE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_LINK_NEGOTIATION_DONE) || \
    false)

static inline void trace_nvnet_link_negotiation_done(void)
{
    if (trace_event_get_state(TRACE_NVNET_LINK_NEGOTIATION_DONE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_link_negotiation_done " "Auto negotiation is completed" "\n");
#line 302 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_LINK_STATUS_CHANGED_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_LINK_STATUS_CHANGED) || \
    false)

static inline void trace_nvnet_link_status_changed(bool status)
{
    if (trace_event_get_state(TRACE_NVNET_LINK_STATUS_CHANGED)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_link_status_changed " "New link status: %d" "\n", status);
#line 317 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_CANT_RX_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_CANT_RX) || \
    false)

static inline void trace_nvnet_cant_rx(bool rx_en, bool dma_en, bool link_up, bool buf_avail)
{
    if (trace_event_get_state(TRACE_NVNET_CANT_RX)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 20 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_cant_rx " "rx_en:%d dma_en:%d link_up:%d buf_avail:%d" "\n", rx_en, dma_en, link_up, buf_avail);
#line 332 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_CANT_TX_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_CANT_TX) || \
    false)

static inline void trace_nvnet_cant_tx(bool tx_en, bool dma_en, bool link_up)
{
    if (trace_event_get_state(TRACE_NVNET_CANT_TX)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 21 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_cant_tx " "tx_en:%d dma_en:%d link_up:%d" "\n", tx_en, dma_en, link_up);
#line 347 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_UPDATE_IRQ_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_UPDATE_IRQ) || \
    false)

static inline void trace_nvnet_update_irq(uint32_t status, uint32_t mask)
{
    if (trace_event_get_state(TRACE_NVNET_UPDATE_IRQ)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_update_irq " "status 0x%"PRIx32" mask 0x%"PRIx32 "\n", status, mask);
#line 362 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_DESC_STORE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_DESC_STORE) || \
    false)

static inline void trace_nvnet_desc_store(uint32_t desc_addr, uint32_t buf_addr, uint16_t length, uint16_t flags)
{
    if (trace_event_get_state(TRACE_NVNET_DESC_STORE)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 23 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_desc_store " "addr 0x%"PRIx32" buf 0x%"PRIx32" length 0x%"PRIx16" flags 0x%"PRIx16 "\n", desc_addr, buf_addr, length, flags);
#line 377 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_RX_DMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_RX_DMA) || \
    false)

static inline void trace_nvnet_rx_dma(uint32_t addr, size_t size)
{
    if (trace_event_get_state(TRACE_NVNET_RX_DMA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 24 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_rx_dma " "addr 0x%"PRIx32" size 0x%zx" "\n", addr, size);
#line 392 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_TX_DMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_TX_DMA) || \
    false)

static inline void trace_nvnet_tx_dma(uint32_t addr, size_t size)
{
    if (trace_event_get_state(TRACE_NVNET_TX_DMA)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 25 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_tx_dma " "addr 0x%"PRIx32" size 0x%zx" "\n", addr, size);
#line 407 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}

#define TRACE_NVNET_PACKET_TX_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_NVNET_PACKET_TX) || \
    false)

static inline void trace_nvnet_packet_tx(size_t size)
{
    if (trace_event_get_state(TRACE_NVNET_PACKET_TX)) {
        if (qemu_loglevel_mask(LOG_TRACE)) {
#line 26 "../hw/xbox/mcpx/nvnet/trace-events"
            qemu_log("nvnet_packet_tx " "size 0x%zx" "\n", size);
#line 422 "trace/trace-hw_xbox_mcpx_nvnet.h"
        }
    }
}
#endif /* TRACE_HW_XBOX_MCPX_NVNET_GENERATED_TRACERS_H */
